nfl_teams = {
    "Dallas Cowboys":"DAL",
    "Miami Dolphins":"MIA",
    "Chicago Bears":"CHI",
    "Oakland Raiders":"OAK",
    "Green Bay Packers":"GB",
    "San Francisco 49ers":"SF",
    "Minnesota Vikings":"MIN",
    "New York Giants":"NYG",
    "Baltimore Ravens":"BAL",
    "Denver Broncos":"DEN",
    "Cleveland Browns":"CLE",
    "Jacksonville Jaguars":"JAX",
    "Indianapolis Colts":"IND",
    "New England Patriots":"NE",
    "Kansas City Chiefs":"KC",
    "Los Angeles Rams":"LA",
    "Carolina Panthers":"CAR",
    "Tennessee Titans":"TEN",
    "San Diego Chargers":"SD",
    "Seattle Seahawks":"SEA",
    "Buffalo Bills":"BUF",
    "Philadelphia Eagles":"PHI",
    "Detroit Lions":"DET",
    "New York Jets":"NYJ",
    "Cincinnati Bengals":"CIN",
    "Atlanta Falcons":"ATL",
    "New Orleans Saints":"NO",
    "Arizona Cardinals":"ARI",
    "Tampa Bay Buccaneers":"TB",
    "Houston Texans":"HOU"
}

ncaa_fb_teams = {
    "Air Force":"AF",
    "Akron":"AKRN",
    "Alabama":"BAMA",
    "Alabama Birmingham":"UAB",
    "Arizona":"ARIZ",
    "Arizona State":"AZST",
    "Arkansas":"ARK",
    "Arkansas State":"ARST",
    "Army":"ARMY",
    "Auburn":"AUB",
    "Ball State":"BALL",
    "Baylor":"BAY",
    "Boise State":"BOISE",
    "Boston College":"BC",
    "Bowling Green":"BG",
    "Brigham Young":"BYU",
    "Buffalo":"BUF",
    "California":"CAL",
    "Central Florida":"UCF",
    "Central Michigan":"CMU",
    "Cincinnati":"CIN",
    "Clemson":"CLEM",
    "Colarado":"COL",
    "Colarado State":"CSU",
    "Connecticut":"CONN",
    "Duke":"DUKE",
    "East Carolina":"ECU",
    "Eastern Michigan":"EMU",
    "Florida":"UF",
    "Florida Atlantic":"FAU",
    "Florida International":"FIU",
    "Florida State":"FSU",
    "Fresno State":"FRSNO",
    "Georgia":"UGA",
    "Georgia Tech":"GTECH",
    "Hawaii":"HAW",
    "Houston":"HOU",
    "Idaho":"IDAHO",
    "Illinois":"ILL",
    "Indiana":"IND",
    "Iowa":"IOWA",
    "Iowa State":"IAST",
    "Kansas":"KAN",
    "Kansas State":"KSST",
    "Kent State":"KENT",
    "Kentucky":"UK",
    "Louisiana State":"LSU",
    "Louisiana Tech":"LTECH",
    "Louisiana Lafayette":"ULL",
    "Louisiana Monroe":"ULM",
    "Louisville":"LOU",
    "Marshall":"MRSHL",
    "Maryland":"MARY",
    "Massachusetts:":"MASS",
    "Memphis":"MEM",
    "Miami":"MIAF",
    "Miami Ohio":"MIAO",
    "Michigan":"MICH",
    "Michigan State":"MIST",
    "Middle Tennessee":"MTENN",
    "Minnesota":"MINN",
    "Mississippi":"MISS",
    "Mississippi State":"MSST",
    "Missouri":"MIZZ",
    "Navy":"NAVY",
    "Nebraska":"NEB",
    "Nevada Las Vegas":"UNLV",
    "Nevada":"NEV",
    "New Mexico":"UNM",
    "North Carolina":"UNC",
    "North Carolina State":"NCST",
    "North Texas":"NTEX",
    "Northern Illinois":"NILL",
    "Northwestern":"NWEST",
    "Notre Dame":"NDAME",
    "Ohio":"OHIO",
    "Ohio State":"OHST",
    "Oklahoma":"OKLA",
    "Oklahoma State":"OKST",
    "Oregon":"OREG",
    "Oregon State":"ORST",
    "Penn State":"PSU",
    "Pittsburgh":"PITT",
    "Purdue":"PURD",
    "Rice":"RICE",
    "Rutgers":"RUTG",
    "San Diego State":"SDSU",
    "San Jose State":"SJSU",
    "South Carolina":"SCAR",
    "South Alabama":"SBAMA",
    "South Florida":"USF",
    "Southern California":"SCAL",
    "Southern Methodist":"SMU",
    "Southern Mississippi":"SMISS",
    "Stanford":"STAN",
    "Syracuse":"SYR",
    "Temple":"TMPLE",
    "Tennessee":"TENN",
    "Texas":"TEX",
    "Texas A&M":"TXAM",
    "Texas Christian":"TCU",
    "Texas State":"TXST",
    "Texas Tech":"TTECH",
    "UTEP":"UTEP",
    "Tex San Antonio":"UTSA",
    "Toledo":"TOL",
    "Troy":"Troy",
    "Tulane":"TLNE",
    "Tulse":"TULSA",
    "UCLA":"UCLA",
    "Utah":"UTAH",
    "Utah State":"UTST",
    "Vanderbilt":"VAND",
    "Virginia":"UVA",
    "Virginia Tech":"VTECH",
    "Wake Forest":"WAKE",
    "Washington":"WASH",
    "Washington State":"WSU",
    "West Virginia":"WVU",
    "Western Kentucky":"WKU",
    "Western Michigan":"WMU",
    "Wisconsin":"WIS",
    "Wyoming":"WYO"
}